apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-r-plus
  labels:
    app: command-r-plus
    cohere.com/confidential-compute: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-r-plus
  template:
    metadata:
      labels:
        app: command-r-plus
        cohere.com/confidential-compute: "true"
      annotations:
        io.katacontainers.config.hypervisor.machine_type: "a3-highgpu-1g"
        io.katacontainers.config.runtime.create_container_timeout: "600"
        io.katacontainers.config.hypervisor.default_gpus: "8"
        io.katacontainers.config.hypervisor.image: "projects/cohere-confidential-computing/global/images/ubuntu-mkosi-tdx-debug-2026-03-27"
    spec:
      runtimeClassName: kata-remote
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cohere
          image: us-central1-docker.pkg.dev/cohere-artifacts/cohere/single-serving-cohere-all:v0.14.1-04162026
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: "8"
