targets:
- model: new-model
  machine_type: a3-highgpu-1g
  podvm_image_tag: podvm-v1
  ram_gib: 234
  initdata_b64: dGVzdC1pbml0ZGF0YS1uZXc=
  added: "2026-07-01"
  sources:
    - 112233aa112233aa112233aa112233aa112233aa
- model: existing-model
  machine_type: a3-highgpu-1g
  podvm_image_tag: podvm-v1
  ram_gib: 234
  initdata_b64: dGVzdC1pbml0ZGF0YS1leGlzdGluZw==
  added: "2026-07-01"
  sources:
    - 112233aa112233aa112233aa112233aa112233aa
